export const serverImports = [
  { name: 'loginHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'logoutHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'signUpHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'OAuthRedirect', from: '@riavzon/auth-h3client/v1' },
  { name: 'OAuthSuccessCallBack', from: '@riavzon/auth-h3client/v1' },
  { name: 'restartPasswordHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'sendMfaCodeHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'sendNewPasswordHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'verifyTempPasswordLink', from: '@riavzon/auth-h3client/v1' },
  { name: 'verifyTempMfaLink', from: '@riavzon/auth-h3client/v1' },
  { name: 'defineAuthConfiguration', from: '@riavzon/auth-h3client/v1' },
  { name: 'defineAuthenticatedEventHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'defineOptionalAuthenticationEvent', from: '@riavzon/auth-h3client/v1' },
  { name: 'defineVerifiedCsrfHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'defineAuthenticatedEventPostHandlers', from: '@riavzon/auth-h3client/v1' },
  { name: 'defineDeduplicatedEventHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'getAuthStatusHandler', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'generateCsrfCookie', from: '@riavzon/auth-h3client/v1' },
  { name: 'verifyCsrfCookie', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'ensureValidCredentials', from: '@riavzon/auth-h3client/v1' },
  { name: 'OAuthTokensValidations', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'isIPValid', from: '@riavzon/auth-h3client/v1' },
  { name: 'botDetectorMiddleware', from: '@riavzon/auth-h3client/v1' },
  { name: 'hmacSignatureMiddleware', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'httpLogger', from: '@riavzon/auth-h3client/v1' },
  { name: 'limitBytes', from: '@riavzon/auth-h3client/v1' },
  { name: 'contentType', from: '@riavzon/auth-h3client/v1' },
  { name: 'notFoundHandler', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'useAuthRoutes', from: '@riavzon/auth-h3client/v1' },
  { name: 'useOAuthRoutes', from: '@riavzon/auth-h3client/v1' },
  { name: 'magicLinksRouter', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'makeCookie', from: '@riavzon/auth-h3client/v1' },
  { name: 'createSignedValue', from: '@riavzon/auth-h3client/v1' },
  { name: 'verifySignedValue', from: '@riavzon/auth-h3client/v1' },
  { name: 'toB64', from: '@riavzon/auth-h3client/v1' },
  { name: 'fromB64', from: '@riavzon/auth-h3client/v1' },
  { name: 'isSameBuffer', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'safeRedirect', from: '@riavzon/auth-h3client/v1'},
  { name: 'bounceRouter', from: '@riavzon/auth-h3client/v1' },
  { name: 'serviceToService', from: '@riavzon/auth-h3client/v1' },
  { name: 'clientHeaders', from: '@riavzon/auth-h3client/v1' },
  { name: 'signature', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'getAccessTokenMetaData', from: '@riavzon/auth-h3client/v1' },
  { name: 'getCachedUserData', from: '@riavzon/auth-h3client/v1' },
  { name: 'getOperationalConfig', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'discoverOidc', from: '@riavzon/auth-h3client/v1' },
  { name: 'makePkcePair', from: '@riavzon/auth-h3client/v1' },
  { name: 'verifyOAuthToken', from: '@riavzon/auth-h3client/v1' },
  { name: 'atHashCheck', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'throwHttpError', from: '@riavzon/auth-h3client/v1' },
  { name: 'lockAsyncAction', from: '@riavzon/auth-h3client/v1' },
  { name: 'getLogger', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'getBaseUrl', from: '@riavzon/auth-h3client/v1' },
  { name: 'parseResponseContentType', from: '@riavzon/auth-h3client/v1' },
  { name: 'findStringsInObject', from: '@riavzon/auth-h3client/v1' },
  { name: 'safeObjectMerge', from: '@riavzon/auth-h3client/v1' },
  { name: 'MiniCache', from: '@riavzon/auth-h3client/v1' },
  { name: 'getAuthAgent', from: '@riavzon/auth-h3client/v1' },
  { name: 'banIp', from: '@riavzon/auth-h3client/v1' },
  { name: 'applyRotationResult', from: '@riavzon/auth-h3client/v1' },
  { name: 'checkForBots', from: '@riavzon/auth-h3client/v1' },
  { name: 'getSafeUrl', from: '@riavzon/auth-h3client/v1' },
  { name: 'configuration', from: '@riavzon/auth-h3client/v1' },
  { name: 'getConfiguration', from: '@riavzon/auth-h3client/v1' },
  
  { name: 'sanitizeInputString', from: '@riavzon/auth-h3client/v1' },
  { name: 'sanitizeBaseName', from: '@riavzon/auth-h3client/v1' },
  { name: 'validateImage', from: '@riavzon/auth-h3client/v1' },
  { name: 'makeSafeString', from: '@riavzon/auth-h3client/v1' },
  { name: 'validateUserPassword', from: '@riavzon/auth-h3client/v1' },
  { name: 'askForMfaFlow', from: '@riavzon/auth-h3client/v1' },
  { name: 'defineVerifiedMagicLinkGetHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'defineMfaCodeVerifierHandler', from: '@riavzon/auth-h3client/v1' },
  { name: 'initEmailChangeFlow', from: '@riavzon/auth-h3client/v1' },
  { name: 'changeEmailGetAPI', from: '@riavzon/auth-h3client/v1' },
  { name: 'updateNewEmail', from: '@riavzon/auth-h3client/v1' },
  { name: 'validateZodSchema', from: '@riavzon/auth-h3client/v1' }
] as const;
