import handleLogin from "./controllers/handleLogin.js";
import handleSignUps from "./controllers/handleSignUps.js";
import restartPasswordController from "./controllers/restartPasswordController.js";
import sendMfaCode from "./controllers/sendMfaCode.js";
import sendNewPassword from "./controllers/sendNewPassword.js";
import verifyTempLink from "./controllers/verifyTempLink.js";
import csrf from "./middleware/csrf.js";
import throwError from "./middleware/error.js";
import isValidIP from "./middleware/isValidIP.js";
import signatureMiddleware from "./middleware/signatureMiddleware.js";
import verifyCsrf from "./middleware/verifyCsrf.js";

export { configuration, getConfiguration } from "./config/config.js";
export const loginHandler = handleLogin
export {handleLogout} from "./controllers/handleLogout.js";
export const signUpHandler = handleSignUps;
export { OAuthRedirect } from "./controllers/OAuthRedirect.js";
export { OAuthCallback } from "./controllers/OAuthSuccessCallBack.js";
export const restartPasswordHandler = restartPasswordController;
export const sendMfaCodeHandler = sendMfaCode;
export const sendNewPasswordHandler = sendNewPassword;
export const verifyTempLinkHandler = verifyTempLink;
export const generateCsrfCookie = csrf;
export const throwHttpError = throwError;
export { ensureAccessToken } from "./middleware/getAccessToken.js";
export { ensureRefreshCookie } from "./middleware/getRefreshToken.js";
export { httpLogger } from "./middleware/httpLogger.js";
export const isIPValid = isValidIP;
export { limitBytes } from "./middleware/limitBytes.js";
export { notFoundHandler } from "./middleware/notFound.js";
export { OAuthTokensValidations } from "./middleware/OAuthCallBack.js";
export { ensureValidCredentials } from "./middleware/rotateTokens.js";
export const hmacSignatureMiddleware = signatureMiddleware;
export { contentType } from "./middleware/validateContentType.js";
export const verifyCsrfCookie = verifyCsrf;
export { validator as botDetectorMiddleware } from "./middleware/visitorValid.js";
export { useAuthRoutes } from "./routes/auth.js";
export { magicLinksRouter } from "./routes/magicLinks.js";
export { useOAuthRoutes } from "./routes/OAuth.js";
export { atHashCheck } from "./utils/atHash.js";
export { banIp } from "./utils/banIp.js";
export { getBaseUrl } from "./utils/buildBaseUrl.js";
export { parseResponseContentType } from "./utils/checkResponseType.js";
export { clientHeaders } from "./utils/clientHeaders.js";
export { makeCookie } from "./utils/cookieGenerator.js";
export { toB64, fromB64, isSame as isSameBuffer, createSignedCookie as createSignedValue, verifySignedCookie as verifySignedValue } from "./utils/cryptoCookies.js";
export { discoverOidc } from "./utils/discoverOidc.js";
export { findStringsInObject } from "./utils/findObjectValues.js";
export { getMetadata as getAccessTokenMetaData } from "./utils/getAccessTokenMetaData.js";
export { getMetadata as getRefreshTokenMetaData} from "./utils/getRefreshTokenMetaData.js";
export { getOperationalConfig } from "./utils/getRemoteConfig.js";
export { getLogger } from "./utils/logger.js";
export { MiniCache } from "./utils/miniCache.js";
export { makePkcePair } from "./utils/pkce.js";
export { safeObjectMerge } from "./utils/safeMerge.js";
export { getAuthAgent } from "./utils/serverAuth.js";
export { signature } from "./utils/serverSignature.js";
export { sendToServer as serviceToService} from "./utils/serverToServer.js";
export { sendLog as sendTelegramMessage } from "./utils/telegramLogger.js";
export { verifyOAuthToken } from "./utils/verifyOAuthTokens.js";
