 services:
  mysql-test:
    image: mysql:8.0
    restart: unless-stopped
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: very_secure_password_for_tests
      MYSQL_DATABASE: my_auth_tests_db
      MYSQL_USER: sergio
      MYSQL_PASSWORD: very_secure_password_for_tests
    ports:
      - "3308:3306" 
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/3306'"]
      interval: 10s
      timeout: 8s 
      retries: 5
      start_period: 7m
    tmpfs:
      - /var/lib/mysql:rw,noexec,nosuid,nodev,size=512m 
    networks:
      test_backend_h3client:
        ipv4_address: 172.28.5.3  
      test_h3client_egress: 
        ipv4_address: 172.29.20.2 
        
  auth-test:
    image: sergio68/auth
    entrypoint: ["node", "dist/service.mjs"]
    read_only: false
    environment:
      CONFIG_PATH: /app/configs/auth-config.json
      SKIP_CONFIG_UNLINK: "true"
    restart: unless-stopped
    cap_drop: ["ALL"]
    user: 0:0
    volumes: 
      - ./auth-logs/server:/app/auth-logs:rw
      - ./auth-logs/server/bot-detector:/app/bot-detector-logs:rw
      - ./test/setup/configs/:/app/configs/:rw
      - email-data:/app/dist/email-db:rw
      - bot-detector-data:/app/node_modules/@riavzon/bot-detector/dist/_data-sources:rw
    pids_limit: 200
    depends_on:
      mysql-test:
        condition: service_healthy
    ports:
      - "10002:10000"
    security_opt: 
      - "no-new-privileges:true"
    networks:
      test_backend_h3client:
        ipv4_address: 172.28.5.4  
      test_h3client_egress: 
        ipv4_address: 172.29.20.3 
 volumes:
  bot-detector-data:
  email-data:
 networks: 
  test_backend_h3client: 
    internal: true
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.1
  test_h3client_egress:
    internal: false
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.29.20.0/24
          gateway: 172.29.20.1