import { defineConfig, type Options } from 'tsup';

const serverConfig: Options = {
  entry: {
    'v1': 'packages/client-h3v1/src/main.ts',
    'v2': 'packages/client-h3v2/src/main.ts',
    'module': 'packages/client/module.ts',
    'server/middleware': 'packages/client/server/middleware/auth.ts',
    'server/templates': 'packages/client/server/templates/index.ts',
    'server/routes': 'packages/client/server/routes/authStatus.ts',
  },
  format: ['esm'],
  tsconfig: 'tsconfig.prod.json',
  dts: true,
  sourcemap: true,
  clean: false,  
  splitting: true,
  outDir: 'dist',
  external: [
    'node:crypto',
    'node:buffer',
    'node:net',
    'crypto',
    'fs',
    'path',
    'url',
    'child_process',
    'h3',
    'vue',
    'nuxt',
    'nuxt/app',
    '@nuxt/kit',
    'nitropack',
    'nitropack/runtime',
    'jose',
    'zod',
    'pino',
    'undici',
    'unstorage',
  ],
  noExternal: [
    '@internal/shared',
  ],
  treeshake: true,
};

const clientConfig: Options = {
  entry: {
    'client': 'packages/client/main.ts',
  },
  format: ['esm'],
  tsconfig: 'tsconfig.prod.json',
  dts: true,
  sourcemap: true,
  clean: false,
  splitting: false,
  outDir: 'dist',
  noExternal: ['@internal/shared'],
  external: [
    'vue',
    'nuxt',
    'nuxt/app',
    'node:crypto',
    'node:buffer', 
    'node:net',
    'crypto',
    'fs',
    'path',
    'url',
    'child_process',
    'h3',
    '@nuxt/kit',
    'nitropack',
    'nitropack/runtime',
    'jose',
    'zod',
    'pino',
    'undici',
    'unstorage',
    'ofetch',
  ],
  treeshake: true,
};

export default defineConfig([clientConfig, serverConfig]);