import handleLogin from "./controllers/handleLogin.js";
import handleSignUps from "./controllers/handleSignUps.js";
import restartPasswordController from "./controllers/restartPasswordController.js";
import sendMfaCode from "./controllers/sendMfaCode.js";
import sendNewPassword from "./controllers/sendNewPassword.js";
import verifyTempLink from "./controllers/verifyTempLink.js";
import csrf from "./middleware/csrf.js";
import throwError from "./middleware/error.js";
import isValidIP from "./middleware/isValidIP.js";
import signatureMiddleware from "./middleware/signatureMiddleware.js";
import verifyCsrf from "./middleware/verifyCsrf.js";
import handleLogout from "./controllers/handleLogout.js";
import OAuthCallBack from "./controllers/OAuthSuccessCallBack.js";

export { configuration, getConfiguration } from "@internal/shared";
export const loginHandler = handleLogin
export const logoutHandler = handleLogout;
export const signUpHandler = handleSignUps;
export const OAuthSuccessCallBack = OAuthCallBack;
export { OAuthRedirect } from "./controllers/OAuthRedirect.js";
export const restartPasswordHandler = restartPasswordController;
export const sendMfaCodeHandler = sendMfaCode;
export const sendNewPasswordHandler = sendNewPassword;
export const verifyTempLinkHandler = verifyTempLink;
export const generateCsrfCookie = csrf;
export const throwHttpError: typeof throwError = throwError;
export { ensureAccessToken } from "./middleware/getAccessToken.js";
export { ensureRefreshCookie } from "./middleware/getRefreshToken.js";
export { httpLogger } from "./middleware/httpLogger.js";
export const isIPValid = isValidIP;
export { limitBytes } from "./middleware/limitBytes.js";
export { notFoundHandler } from "./middleware/notFound.js";
export { OAuthTokensValidations } from "./middleware/OAuthCallBack.js";
export { ensureValidCredentials } from "./middleware/rotateTokens.js";
export const hmacSignatureMiddleware = signatureMiddleware;
export { contentType } from "./middleware/validateContentType.js";
export const verifyCsrfCookie = verifyCsrf;
export { validator as botDetectorMiddleware } from "./middleware/visitorValid.js";
export { useAuthRoutes } from "./routes/auth.js";
export { magicLinksRouter } from "./routes/magicLinks.js";
export { useOAuthRoutes } from "./routes/OAuth.js";
export { atHashCheck } from "@internal/shared";
export { banIp } from "@internal/shared";
export { getBaseUrl } from "@internal/shared";
export { parseResponseContentType } from "@internal/shared";
export { clientHeaders } from "./utils/clientHeaders.js";
export { makeCookie } from "./utils/cookieGenerator.js";
export { toB64, fromB64, isSame as isSameBuffer, createSignedCookie as createSignedValue, verifySignedCookie as verifySignedValue } from "@internal/shared";
export { discoverOidc } from "@internal/shared";
export { findStringsInObject } from "@internal/shared";
export { getMetadata as getAccessTokenMetaData } from "./utils/getAccessTokenMetaData.js";
export { getMetadata as getRefreshTokenMetaData} from "./utils/getRefreshTokenMetaData.js";
export { getOperationalConfig } from "./utils/getRemoteConfig.js";
export { getLogger } from "@internal/shared";
export { MiniCache } from "@internal/shared";
export { makePkcePair } from "@internal/shared";
export { safeObjectMerge } from "@internal/shared";
export { getAuthAgent } from "@internal/shared";
export { signature } from "@internal/shared";
export { sendToServer as serviceToService} from "./utils/serverToServer.js";
export { sendLog as sendTelegramMessage } from "@internal/shared";
export { verifyOAuthToken } from "@internal/shared";
export {applyRotationResult} from "./utils/applyRotationResults.js"
export {safeAction as lockAsyncAction} from "@internal/shared"
export { sanitizeInputString, sanitizeBaseName, validateImage, makeSafeString } from "@internal/shared";
export {checkForBots} from "./utils/checkForBots.js";
export { defineAuthConfiguration } from "./nitroPluginStarter.js";
export { defineAuthenticatedEventHandler, type MfaResponse } from "./utils/defineAuthRoute.js";
export { defineOptionalAuthenticationEvent } from "./utils/defineOptionalAuth.js";
export { getAuthStatusHandler } from "./utils/getAuthStatus.js";
export { defineVerifiedCsrfHandler } from "./utils/csrfVerifier.js";
export { defineAuthenticatedEventPostHandlers } from "./utils/authenticatedPostHandler.js";
export { defineDeduplicatedEventHandler } from "./utils/requestDedupHandler.js";
export { getCachedUserData } from "./utils/getCachedUserData.js";
export { type H3Event, defineEventHandler, appendResponseHeader, getRequestURL, isMethod, sendNoContent, getHeader } from 'h3';